package eu.heha.applicator.ui.document

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Star
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import eu.heha.applicator.ui.theme.ApplicatorTheme

@Composable
fun ApplicationDocumentContainer(
    model: ApplicationContainerModel,
    content: @Composable () -> Unit = {}
) {
    Column(
        Modifier
            .fillMaxSize()
            .padding(32.dp)
    ) {
        Header(
            name = model.name,
            subtitle = model.subtitle,
            contactInfo = model.contactInfo
        )
        Box(modifier = Modifier.weight(1f)) {
            content()
        }
        Footer(model.footLine)
    }
}

@Composable
private fun Header(name: String, subtitle: String, contactInfo: List<String>) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            modifier = Modifier.weight(1f)
        ) {
            Text(name, style = MaterialTheme.typography.headlineSmall)
            Text(subtitle, style = MaterialTheme.typography.titleMedium)
        }

        Box(modifier = Modifier.padding(16.dp)) {
            Image(
                imageVector = Icons.Default.Star,
                contentDescription = null,
                modifier = Modifier.size(48.dp)
            )
        }

        Column(
            horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)
        ) {
            contactInfo.forEach { contact ->
                Text(contact, style = MaterialTheme.typography.titleSmall)
            }
        }
    }
}

@Composable
private fun Footer(footLine: String) {
    Text(
        text = footLine,
        style = MaterialTheme.typography.bodySmall,
        textAlign = TextAlign.Center,
        modifier = Modifier.fillMaxWidth()
    )
}

data class ApplicationContainerModel(
    val name: String,
    val subtitle: String,
    val contactInfo: List<String>,
    val footLine: String
)

fun defaultContainerModel() = ApplicationContainerModel(
    name = "Max Mustermann",
    subtitle = "Software Developer",
    contactInfo = listOf("mail: max@mustermann.de", "github: max-mustermann"),
    footLine = "Generated by Applicator, for more see https://github.com/sihamark/ComposeToPdf"
)

@Preview(
    widthDp = 595,
    heightDp = 842,
    backgroundColor = 0xFFFFFFFF,
    showBackground = true
)
@Composable
private fun DocumentContentPreview() {
    ApplicatorTheme {
        ApplicationDocumentContainer(defaultContainerModel())
    }
}